sonar.projectKey=invest-int-bank-portal
sonar.projectName=Invest Int Bank Portal
sonar.projectVersion=1.0.0
sonar.sources=src,firestore.rules,firebase.json
sonar.exclusions=dist/**,node_modules/**,exports/**,.firebase/**
sonar.sourceEncoding=UTF-8
